(function () {
  const storage = window.CodeWhatsStorage;
  let state = null;
  let modal = null;
  let query = "";

  const esc = (value) => String(value || "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#039;");
  const clean = (value) => String(value || "").replace(/\s+/g, " ").trim();
  const phone = (value) => clean(value).replace(/\D/g, "");
  const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 });
  const activeFunnel = () => state.funis.find((funil) => funil.id === state.activeFunnelId) || state.funis[0];
  const filteredClients = () => {
    const q = query.toLowerCase();
    return state.clientes.filter((c) => c.funilId === activeFunnel().id && (!q || [c.nome, c.telefone, c.observacao, ...(c.tags || [])].join(" ").toLowerCase().includes(q)));
  };
  const clientsFor = (etapaId) => filteredClients().filter((cliente) => cliente.etapaId === etapaId);

  function render() {
    const funil = activeFunnel();
    document.querySelector('[data-role="crm-app"]').innerHTML = `
      <header class="cwl-crm-header">
        <div><p class="cwl-kicker">CRM completo</p><h1>CODE Whats Local</h1></div>
        <div class="cwl-inline-actions">
          <label class="cwl-field"><span>Funil</span><select data-action="change-funnel">${state.funis.map((f) => `<option value="${f.id}" ${f.id === funil.id ? "selected" : ""}>${esc(f.nome)}</option>`).join("")}</select></label>
          <input class="cwl-crm-search" data-action="search" placeholder="Buscar cliente ou conversa" value="${esc(query)}">
          <button class="cwl-btn cwl-btn-ghost" data-action="new-funnel">Novo funil</button>
          <button class="cwl-btn cwl-btn-ghost" data-action="rename-funnel">Renomear funil</button>
          <button class="cwl-btn cwl-btn-ghost" data-action="delete-funnel">Excluir funil</button>
          <button class="cwl-btn cwl-btn-ghost" data-action="new-column">Nova etapa</button>
          <button class="cwl-btn cwl-btn-primary" data-action="new-client">Novo card</button>
          <button class="cwl-btn cwl-btn-ghost" data-action="import-csv">Importar CSV</button>
          <button class="cwl-btn cwl-btn-ghost" data-action="messages">Mensagens</button>
          <input class="cwl-file-input" type="file" accept=".csv,text/csv" data-role="csv-file">
        </div>
      </header>
      <section class="cwl-crm-board">
        ${renderDetectedColumn()}
        ${funil.etapas.map(renderColumn).join("")}
      </section>
      ${renderModal()}
    `;
  }

  function renderDetectedColumn() {
    const chats = (state.detectedChats || []).filter((chat) => !query || [chat.nome, chat.name, chat.ultimaMensagem, chat.lastMessage].join(" ").toLowerCase().includes(query.toLowerCase()));
    return `<article class="cwl-crm-column cwl-inbox-column"><header><h2>Conversas em andamento</h2><span>${chats.length}</span></header><div class="cwl-crm-dropzone cwl-crm-inbox-zone">${chats.map(renderDetectedCard).join("") || `<p class="cwl-empty">Abra o WhatsApp Web para sincronizar conversas visíveis.</p>`}</div></article>`;
  }
  function renderDetectedCard(chat) { return `<article class="cwl-card cwl-detected-card" draggable="true" data-detected-key="${esc(chat.key)}"><div class="cwl-card-top"><div><strong>${esc(chat.nome || chat.name)}</strong><span>${esc(chat.ultimaMensagem || chat.lastMessage || "Conversa detectada")}</span></div></div><div class="cwl-card-meta"><span>${esc(chat.ultimoContato || chat.lastMessageTime || "")}</span><button data-action="add-detected" data-detected-key="${esc(chat.key)}">Adicionar</button></div></article>`; }
  function renderColumn(etapa) { const clients = clientsFor(etapa.id); return `<article class="cwl-crm-column" data-column-id="${etapa.id}"><header><input class="cwl-column-title" data-action="rename-column-inline" data-column-id="${etapa.id}" value="${esc(etapa.nome)}"><span>${clients.length}</span><button data-action="delete-column" data-column-id="${etapa.id}">×</button></header><div class="cwl-crm-dropzone" data-column-id="${etapa.id}">${clients.map(renderClientCard).join("") || `<p class="cwl-empty">Sem cards.</p>`}</div></article>`; }
  function renderClientCard(c) { return `<article class="cwl-card" draggable="true" data-client-id="${c.id}"><div class="cwl-card-top"><div><strong>${esc(c.nome)}</strong><span>${esc(c.telefone || c.waKey)}</span></div><em class="cwl-temp cwl-temp-${c.temperatura}">${esc(c.temperatura)}</em></div><div class="cwl-tags">${(c.tags || []).slice(0, 3).map((t) => `<span>${esc(t)}</span>`).join("")}</div>${c.proximaAcao ? `<p class="cwl-next">${esc(c.proximaAcao)}</p>` : ""}<div class="cwl-card-meta"><span>${money.format(c.valor || 0)}</span><span>${esc(c.origem)}</span></div><div class="cwl-card-actions"><button data-action="open-whatsapp" data-client-id="${c.id}">Abrir conversa</button><button data-action="copy-message" data-client-id="${c.id}">Copiar mensagem</button><button data-action="edit-client" data-client-id="${c.id}">Editar</button><button data-action="delete-client" data-client-id="${c.id}">Excluir</button></div></article>`; }

  function renderModal() {
    if (!modal) return "";
    if (modal.type === "client") return renderClientModal();
    if (modal.type === "detected") return renderDetectedModal();
    if (modal.type === "csv") return renderCsvModal();
    if (modal.type === "messages") return renderMessagesModal();
    return "";
  }
  function funilOptions(selected) { return state.funis.map((f) => `<option value="${f.id}" ${f.id === selected ? "selected" : ""}>${esc(f.nome)}</option>`).join(""); }
  function etapaOptions(funilId, selected) { const f = state.funis.find((x) => x.id === funilId) || activeFunnel(); return f.etapas.map((e) => `<option value="${e.id}" ${e.id === selected ? "selected" : ""}>${esc(e.nome)}</option>`).join(""); }
  function renderClientModal() { const c = modal.clientId ? state.clientes.find((x) => x.id === modal.clientId) : null; const funilId = modal.funilId || (c ? c.funilId : activeFunnel().id); const etapaId = c && c.funilId === funilId ? c.etapaId : ((state.funis.find((f) => f.id === funilId) || activeFunnel()).etapas[0].id); return `<div class="cwl-modal-backdrop" data-action="close-modal"><form class="cwl-modal" data-role="client-form"><header><h2>${c ? "Editar card" : "Novo card"}</h2><button type="button" class="cwl-icon-btn" data-action="close-modal">×</button></header><div class="cwl-form-grid">${input("Nome", "nome", c && c.nome, "text", true)}${input("Telefone", "telefone", c && c.telefone, "tel")}<label class="cwl-field"><span>Funil</span><select name="funilId" data-action="modal-funnel-change">${funilOptions(funilId)}</select></label><label class="cwl-field"><span>Etapa</span><select name="etapaId">${etapaOptions(funilId, etapaId)}</select></label>${input("Etiquetas", "tags", c && (c.tags || []).join(", "))}<label class="cwl-field"><span>Temperatura</span><select name="temperatura">${["frio", "morno", "quente"].map((t) => `<option value="${t}" ${c && c.temperatura === t ? "selected" : ""}>${t}</option>`).join("")}</select></label>${input("Valor", "valor", c && c.valor, "number")}${input("Proxima acao", "proximaAcao", c && c.proximaAcao)}<label class="cwl-field cwl-field-wide"><span>Observacao</span><textarea name="observacao" rows="3">${esc(c && c.observacao)}</textarea></label></div><footer><button class="cwl-btn cwl-btn-ghost" type="button" data-action="close-modal">Cancelar</button><button class="cwl-btn cwl-btn-primary" type="submit">Salvar</button></footer></form></div>`; }
  function renderDetectedModal() { const chat = (state.detectedChats || []).find((x) => x.key === modal.detectedKey); const funil = state.funis.find((f) => f.id === modal.funilId) || activeFunnel(); return `<div class="cwl-modal-backdrop" data-action="close-modal"><form class="cwl-modal" data-role="detected-form"><header><h2>Adicionar conversa</h2><button type="button" class="cwl-icon-btn" data-action="close-modal">×</button></header><p>${esc(chat ? (chat.nome || chat.name) : "Conversa")}</p><div class="cwl-form-grid"><label class="cwl-field"><span>Funil</span><select name="funilId" data-action="modal-funnel-change">${funilOptions(funil.id)}</select></label><label class="cwl-field"><span>Etapa</span><select name="etapaId">${etapaOptions(funil.id, funil.etapas[0].id)}</select></label></div><footer><button class="cwl-btn cwl-btn-ghost" type="button" data-action="close-modal">Cancelar</button><button class="cwl-btn cwl-btn-primary" type="submit">Adicionar</button></footer></form></div>`; }
  function renderCsvModal() { const funil = state.funis.find((f) => f.id === modal.funilId) || activeFunnel(); return `<div class="cwl-modal-backdrop" data-action="close-modal"><form class="cwl-modal" data-role="csv-form"><header><h2>Importar CSV</h2><button type="button" class="cwl-icon-btn" data-action="close-modal">×</button></header><p>Campos: nome, telefone. Opcionais: etiqueta, observacao, valor, temperatura.</p><div class="cwl-form-grid"><label class="cwl-field"><span>Funil</span><select name="funilId" data-action="modal-funnel-change">${funilOptions(funil.id)}</select></label><label class="cwl-field"><span>Etapa</span><select name="etapaId">${etapaOptions(funil.id, funil.etapas[0].id)}</select></label></div><footer><button class="cwl-btn cwl-btn-ghost" type="button" data-action="close-modal">Cancelar</button><button class="cwl-btn cwl-btn-primary" type="submit">Escolher CSV</button></footer></form></div>`; }
  function renderMessagesModal() { return `<div class="cwl-modal-backdrop" data-action="close-modal"><section class="cwl-modal"><header><h2>Mensagens</h2><button type="button" class="cwl-icon-btn" data-action="close-modal">×</button></header><form data-role="template-form" class="cwl-form-grid">${input("Titulo", "titulo", "", "text", true)}<label class="cwl-field cwl-field-wide"><span>Texto</span><textarea name="texto" rows="4" placeholder="Ola {{nome}}, tudo bem?"></textarea></label><button class="cwl-btn cwl-btn-primary" type="submit">Salvar template</button></form><h3>Templates</h3>${state.templates.map((t) => `<article class="cwl-row"><strong>${esc(t.titulo)}</strong><button data-action="delete-template" data-template-id="${t.id}">Excluir</button></article>`).join("") || `<p class="cwl-empty">Nenhum template criado.</p>`}</section></div>`; }
  const input = (label, name, value, type = "text", required = false) => `<label class="cwl-field"><span>${label}</span><input name="${name}" type="${type}" value="${esc(value)}" ${required ? "required" : ""}></label>`;

  function parseCsv(text) { const lines = text.replace(/^\uFEFF/, "").split(/\r?\n/).filter((l) => l.trim()); if (!lines.length) return []; const sep = lines[0].includes(";") ? ";" : ","; const headers = lines[0].split(sep).map((h) => clean(h).toLowerCase()); return lines.slice(1).map((line) => { const cols = line.split(sep); const row = {}; headers.forEach((h, i) => { row[h] = clean(cols[i]); }); return row; }); }
  function personalize(template, cliente) { return template.texto.replace(/{{nome}}/g, cliente.nome || "").replace(/{{telefone}}/g, cliente.telefone || ""); }
  async function openInWhatsApp(cliente) { const tabs = await chrome.tabs.query({ url: "https://web.whatsapp.com/*" }); const url = cliente.telefone ? `https://web.whatsapp.com/send?phone=${cliente.telefone}` : "https://web.whatsapp.com/"; if (!tabs.length) { await chrome.tabs.create({ url }); return; } await chrome.tabs.update(tabs[0].id, { active: true, url: cliente.telefone ? url : undefined }); if (!cliente.telefone) chrome.tabs.sendMessage(tabs[0].id, { type: "CWL_OPEN_CLIENT", clientId: cliente.id }); }
  async function addDetectedAsClient(chat, funilId, etapaId) { state = await storage.upsertClient({ nome: chat.nome || chat.name, telefone: chat.telefone || chat.phone || "", funilId, etapaId, waKey: chat.waKey || chat.key, origem: "whatsapp", observacao: chat.ultimaMensagem || chat.lastMessage, ultimaMensagem: chat.ultimaMensagem || chat.lastMessage, ultimoContato: chat.ultimoContato || chat.lastMessageTime, captured: chat }); }

  document.addEventListener("click", async (event) => { const target = event.target.closest("[data-action], .cwl-card"); if (!target) return; const action = target.dataset.action; if (action === "reload") { state = await storage.getState(); render(); } if (action === "new-funnel") { const name = prompt("Nome do funil:"); if (name) state = await storage.createFunnel(name); render(); } if (action === "rename-funnel") { const name = prompt("Novo nome do funil:", activeFunnel().nome); if (name) state = await storage.renameFunnel(activeFunnel().id, name); render(); } if (action === "delete-funnel") { if (confirm("Excluir funil? Clientes serao movidos para outro funil.")) state = await storage.deleteFunnel(activeFunnel().id); render(); } if (action === "new-column") { const name = prompt("Nome da etapa:"); if (name) state = await storage.createColumn(activeFunnel().id, name); render(); } if (action === "delete-column") { if (confirm("Excluir etapa?")) state = await storage.deleteColumn(activeFunnel().id, target.dataset.columnId); render(); } if (action === "new-client") { modal = { type: "client" }; render(); } if (action === "edit-client") { modal = { type: "client", clientId: target.dataset.clientId }; render(); } if (action === "delete-client") { if (confirm("Excluir card?")) state = await storage.deleteClient(target.dataset.clientId); render(); } if (action === "add-detected") { modal = { type: "detected", detectedKey: target.dataset.detectedKey }; render(); } if (action === "import-csv") { modal = { type: "csv" }; render(); } if (action === "messages") { modal = { type: "messages" }; render(); } if (action === "close-modal") { if (target.matches("button") || target === event.target) { modal = null; render(); } } if (action === "open-whatsapp") { const c = state.clientes.find((x) => x.id === target.dataset.clientId); if (c) openInWhatsApp(c); } if (action === "copy-message") { const c = state.clientes.find((x) => x.id === target.dataset.clientId); if (!c) return; if (!state.templates.length) { alert("Crie um template em Mensagens primeiro."); return; } const title = prompt(`Escolha template:\n${state.templates.map((t, i) => `${i + 1}. ${t.titulo}`).join("\n")}`); const t = state.templates[Number(title) - 1]; if (t) { await navigator.clipboard.writeText(personalize(t, c)); alert("Mensagem copiada."); } } if (action === "delete-template") { state = await storage.deleteTemplate(target.dataset.templateId); render(); } });
  document.addEventListener("input", async (event) => { if (event.target.matches('[data-action="search"]')) { query = event.target.value; render(); } if (event.target.matches('[data-action="rename-column-inline"]')) { clearTimeout(event.target._timer); const inputEl = event.target; inputEl._timer = setTimeout(async () => { state = await storage.renameColumn(activeFunnel().id, inputEl.dataset.columnId, inputEl.value); }, 400); } });
  document.addEventListener("change", async (event) => { if (event.target.matches('[data-action="change-funnel"]')) { state.activeFunnelId = event.target.value; state = await storage.saveState(state); render(); } if (event.target.matches('[data-action="modal-funnel-change"]')) { modal.funilId = event.target.value; render(); } if (event.target.matches('[data-action="modal-funnel-change"]')) { render(); } if (event.target.matches('[data-role="csv-file"]') && event.target.files[0] && modal && modal.csvTarget) { const rows = parseCsv(await event.target.files[0].text()); let imported = 0, ignored = 0, duplicates = 0; for (const row of rows) { const nome = row.nome || row.name; const telefone = phone(row.telefone || row.phone); if (!nome || !telefone) { ignored++; continue; } if (state.clientes.some((c) => c.telefone === telefone)) { duplicates++; continue; } await storage.upsertClient({ nome, telefone, funilId: modal.csvTarget.funilId, etapaId: modal.csvTarget.etapaId, tags: [row.etiqueta].filter(Boolean), observacao: row.observacao, valor: row.valor, temperatura: row.temperatura, origem: "csv" }); imported++; } state = await storage.getState(); modal = null; render(); alert(`CSV importado: ${imported}. Ignorados: ${ignored}. Duplicados: ${duplicates}.`); } });
  document.addEventListener("submit", async (event) => { if (event.target.matches('[data-role="client-form"]')) { event.preventDefault(); const data = new FormData(event.target); const existing = modal.clientId ? state.clientes.find((c) => c.id === modal.clientId) : {}; state = await storage.upsertClient({ ...existing, nome: data.get("nome"), telefone: data.get("telefone"), funilId: data.get("funilId"), etapaId: data.get("etapaId"), tags: clean(data.get("tags")).split(",").map(clean).filter(Boolean), temperatura: data.get("temperatura"), valor: data.get("valor"), proximaAcao: data.get("proximaAcao"), observacao: data.get("observacao"), origem: existing.origem || "manual" }); modal = null; render(); } if (event.target.matches('[data-role="detected-form"]')) { event.preventDefault(); const data = new FormData(event.target); const chat = (state.detectedChats || []).find((x) => x.key === modal.detectedKey); if (chat) await addDetectedAsClient(chat, data.get("funilId"), data.get("etapaId")); state = await storage.getState(); modal = null; render(); } if (event.target.matches('[data-role="csv-form"]')) { event.preventDefault(); const data = new FormData(event.target); modal.csvTarget = { funilId: data.get("funilId"), etapaId: data.get("etapaId") }; document.querySelector('[data-role="csv-file"]').click(); } if (event.target.matches('[data-role="template-form"]')) { event.preventDefault(); const data = new FormData(event.target); state = await storage.upsertTemplate({ titulo: data.get("titulo"), texto: data.get("texto") }); modal = { type: "messages" }; render(); } });
  document.addEventListener("dragstart", (event) => { const card = event.target.closest(".cwl-card"); if (!card) return; if (card.dataset.clientId) event.dataTransfer.setData("application/cwl-client", card.dataset.clientId); if (card.dataset.detectedKey) event.dataTransfer.setData("application/cwl-detected", card.dataset.detectedKey); card.classList.add("is-dragging"); });
  document.addEventListener("dragend", (event) => { const card = event.target.closest(".cwl-card"); if (card) card.classList.remove("is-dragging"); });
  document.addEventListener("dragover", (event) => { const zone = event.target.closest(".cwl-crm-dropzone"); if (zone && !zone.classList.contains("cwl-crm-inbox-zone")) { event.preventDefault(); zone.classList.add("is-over"); } });
  document.addEventListener("dragleave", (event) => { const zone = event.target.closest(".cwl-crm-dropzone"); if (zone) zone.classList.remove("is-over"); });
  document.addEventListener("drop", async (event) => { const zone = event.target.closest(".cwl-crm-dropzone"); if (!zone || zone.classList.contains("cwl-crm-inbox-zone")) return; event.preventDefault(); zone.classList.remove("is-over"); const clientId = event.dataTransfer.getData("application/cwl-client"); const detectedKey = event.dataTransfer.getData("application/cwl-detected"); if (clientId) state = await storage.moveClient(clientId, zone.dataset.columnId); if (detectedKey) { const chat = (state.detectedChats || []).find((x) => x.key === detectedKey); if (chat) await addDetectedAsClient(chat, activeFunnel().id, zone.dataset.columnId); } state = await storage.getState(); render(); });

  async function boot() { state = await storage.getState(); render(); }
  boot();
})();

